"""initial schema

Revision ID: f74ee7deae92
Revises: 
Create Date: 2026-03-07 17:59:22.626589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f74ee7deae92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('combinations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('actions', sqlite.JSON(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('drill_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('plan_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drill_plan_id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_sec', sa.Float(), nullable=False),
    sa.Column('rounds_completed', sa.Integer(), nullable=False),
    sa.Column('rounds_total', sa.Integer(), nullable=False),
    sa.Column('combos_delivered', sa.Integer(), nullable=False),
    sa.Column('delivery_log_json', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_rounds', sa.Integer(), nullable=False),
    sa.Column('default_round_duration_sec', sa.Integer(), nullable=False),
    sa.Column('default_rest_sec', sa.Integer(), nullable=False),
    sa.Column('combo_complexity_range', sqlite.JSON(), nullable=False),
    sa.Column('combo_include_defense', sa.Boolean(), nullable=False),
    sa.Column('pace_interval_sec', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_training_minutes', sa.Float(), nullable=False),
    sa.Column('last_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('combo_exposure_json', sqlite.JSON(), nullable=False),
    sa.Column('template_preference_json', sqlite.JSON(), nullable=False),
    sa.Column('session_frequency', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('session_templates')
    op.drop_table('session_logs')
    op.drop_table('drill_plans')
    op.drop_table('combinations')
    op.drop_table('actions')
    # ### end Alembic commands ###
